networks:
  authelia:
    external: true
    name: authelia

services:
  authelia:
    networks:
      authelia:
        aliases:
          - authelia
    depends_on:
      - lldap
    image: 'docker.io/authelia/authelia:4.39.6'
    container_name: 'authelia'
    restart: unless-stopped
    ports:
      - "9091:9091"
    volumes:
      - './test-configs/authelia:/config'
      - './.test-data/authelia:/data'
      - '/var/log/authelia:/var/log/authelia'
    environment:
      - TZ=UTC
      - AUTHELIA_LOG_LEVEL=debug
      - AUTHELIA_LOG_FORMAT=json
      - AUTHELIA_LOG_FILE_PATH=/var/log/authelia/authelia.log
      - AUTHELIA_LOG_KEEP_STDOUT=true
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9091/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # authelia-admin:
  #   depends_on:
  #     - authelia
  #   image: 'authelia-admin:latest'
  #   container_name: 'authelia-admin'
  #   restart: no
  #   ports:
  #     - "9093:9093"
  #   volumes:
  #     - './test-configs/authelia:/config'
  #     - './.test-data/authelia:/data'
  #   environment:
  #     - TZ=UTC
  #   healthcheck:
  #     test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9093/"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  lldap:
    image: 'docker.io/lldap/lldap:v0.6.2-debian'
    networks:
      authelia:
        aliases:
          - lldap
    container_name: 'lldap'
    restart: no
    volumes:
      - './test-configs/lldap/bootstrap:/bootstrap'
      - './.test-data/lldap:/data'
    ports:
      - "3890:3890" # For LDAP
      - "17170:17170" # For the web front-end
    environment:
      - TZ=UTC
      # envs required for lldap
      - RUST_LOG=debug  # or info, warn, error
      - LLDAP_VERBOSE=true  # Alternative way
      - LLDAP_LDAP_USER_EMAIL=admin@localhost
      - LLDAP_LDAP_USER_PASS=admin1234
      - LLDAP_JWT_SECRET=very_unsecure_jwt_secret_for_testing_only
      - LLDAP_KEY_SEED=very_unsecure_key_seed_for_testing_only
      # envs required for bootstrap.sh
      - LLDAP_ADMIN_USERNAME=admin
      - LLDAP_ADMIN_PASSWORD=admin1234 # same as LLDAP_LDAP_USER_PASS
      - USER_CONFIGS_DIR=/bootstrap/user-configs
      - GROUP_CONFIGS_DIR=/bootstrap/group-configs
      - USER_SCHEMAS_DIR=/bootstrap/user-schemas
      - GROUP_SCHEMAS_DIR=/bootstrap/group-schemas
      - DO_CLEANUP=false

  traefik:
    image: "docker.io/traefik:latest"
    networks:
      authelia:
        aliases:
          - auth.localhost.test
    container_name: "traefik"
    restart: "unless-stopped"
    command:
      - "--configfile=/etc/traefik/traefik.yml"
    ports:
      - "0.0.0.0:443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./test-configs/traefik:/etc/traefik"
      - "./test-configs/traefik/FileProvider:/FileProvider"
      - "/var/log/traefik:/var/log/traefik"